server:
  port: 8083

bot:
  userName: ${BOT_NAME}
  token: ${BOT_TOKEN}
  creatorId: ${BOT_CREATOR_ID}
  chanelId: ${BOT_CHANEL_ID}
#  admin-link: https://t.me/

logging:
  level:
    org:
      springframework:
        web: debug
        jdbc: debug
    root: info
  file:
    path: './'
    name: ${logging.file.path}/test-bot.log